spring:
  application:
    name: jooq-liquibases
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/jooq-test
    #username: admin
    #password: password
    hikari:
      schema: public
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      register-mbeans: true
  jooq:
    sql-dialect: POSTGRES
  liquibase:
    change-log: db/changelog.xml
