version: '3.9'
services:
  postgres:
    image: postgres:16.3
    restart: 'no'
    ports:
      - 5432:5432
    volumes:
      - ./state/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: 'no'
    ports:
      - 5400:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@db.cz
      - PGADMIN_DEFAULT_PASSWORD=postgres
